apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      containers:
      - name: orthanc
        image: orthanc
        ports:
        - containerPort: 8026
        - containerPort: 4026
        volumeMounts:
        - name: orthanc-config
          mountPath: /etc/orthanc
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      automountServiceAccountToken: false
      volumes:
      - name: orthanc-config
        configMap:
          name: orthanc-config
