name: frontend tests workflow
on:
  workflow_call:
jobs:
  unit_tests:
    name: Frontend unit tests
    strategy:
      matrix:
        node-version: [ '12.x', '14.x', '16.x', '18.x' ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
           version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: test with jest
        run: npm run ci-test

